export type Country = {
  value: string;
  label: string;
  phoneCode: string;
  currencyCode: string;
  countryCode: string;
  flag: string;
};

export const countries: Country[] = [
  { value: "AF", label: "Afghanistan", phoneCode: "+93", currencyCode: "AFN", countryCode: "AF", flag: "🇦🇫" },
  { value: "AL", label: "Albania", phoneCode: "+355", currencyCode: "ALL", countryCode: "AL", flag: "🇦🇱" },
  { value: "DZ", label: "Algeria", phoneCode: "+213", currencyCode: "DZD", countryCode: "DZ", flag: "🇩🇿" },
  { value: "AD", label: "Andorra", phoneCode: "+376", currencyCode: "EUR", countryCode: "AD", flag: "🇦🇩" },
  { value: "AO", label: "Angola", phoneCode: "+244", currencyCode: "AOA", countryCode: "AO", flag: "🇦🇴" },
  { value: "AG", label: "Antigua and Barbuda", phoneCode: "+1268", currencyCode: "XCD", countryCode: "AG", flag: "🇦🇬" },
  { value: "AR", label: "Argentina", phoneCode: "+54", currencyCode: "ARS", countryCode: "AR", flag: "🇦🇷" },
  { value: "AM", label: "Armenia", phoneCode: "+374", currencyCode: "AMD", countryCode: "AM", flag: "🇦🇲" },
  { value: "AU", label: "Australia", phoneCode: "+61", currencyCode: "AUD", countryCode: "AU", flag: "🇦🇺" },
  { value: "AT", label: "Austria", phoneCode: "+43", currencyCode: "EUR", countryCode: "AT", flag: "🇦🇹" },
  { value: "AZ", label: "Azerbaijan", phoneCode: "+994", currencyCode: "AZN", countryCode: "AZ", flag: "🇦🇿" },
  { value: "BS", label: "Bahamas", phoneCode: "+1242", currencyCode: "BSD", countryCode: "BS", flag: "🇧🇸" },
  { value: "BH", label: "Bahrain", phoneCode: "+973", currencyCode: "BHD", countryCode: "BH", flag: "🇧🇭" },
  { value: "BD", label: "Bangladesh", phoneCode: "+880", currencyCode: "BDT", countryCode: "BD", flag: "🇧🇩" },
  { value: "BB", label: "Barbados", phoneCode: "+1246", currencyCode: "BBD", countryCode: "BB", flag: "🇧🇧" },
  { value: "BY", label: "Belarus", phoneCode: "+375", currencyCode: "BYN", countryCode: "BY", flag: "🇧🇾" },
  { value: "BE", label: "Belgium", phoneCode: "+32", currencyCode: "EUR", countryCode: "BE", flag: "🇧🇪" },
  { value: "BZ", label: "Belize", phoneCode: "+501", currencyCode: "BZD", countryCode: "BZ", flag: "🇧🇿" },
  { value: "BJ", label: "Benin", phoneCode: "+229", currencyCode: "XOF", countryCode: "BJ", flag: "🇧🇯" },
  { value: "BT", label: "Bhutan", phoneCode: "+975", currencyCode: "BTN", countryCode: "BT", flag: "🇧🇹" },
  { value: "BO", label: "Bolivia", phoneCode: "+591", currencyCode: "BOB", countryCode: "BO", flag: "🇧🇴" },
  {
    value: "BA",
    label: "Bosnia and Herzegovina",
    phoneCode: "+387",
    currencyCode: "BAM",
    countryCode: "BA",
    flag: "🇧🇦",
  },
  { value: "BW", label: "Botswana", phoneCode: "+267", currencyCode: "BWP", countryCode: "BW", flag: "🇧🇼" },
  { value: "BR", label: "Brazil", phoneCode: "+55", currencyCode: "BRL", countryCode: "BR", flag: "🇧🇷" },
  { value: "BN", label: "Brunei", phoneCode: "+673", currencyCode: "BND", countryCode: "BN", flag: "🇧🇳" },
  { value: "BG", label: "Bulgaria", phoneCode: "+359", currencyCode: "BGN", countryCode: "BG", flag: "🇧🇬" },
  { value: "BF", label: "Burkina Faso", phoneCode: "+226", currencyCode: "XOF", countryCode: "BF", flag: "🇧🇫" },
  { value: "BI", label: "Burundi", phoneCode: "+257", currencyCode: "BIF", countryCode: "BI", flag: "🇧🇮" },
  { value: "KH", label: "Cambodia", phoneCode: "+855", currencyCode: "KHR", countryCode: "KH", flag: "🇰🇭" },
  { value: "CM", label: "Cameroon", phoneCode: "+237", currencyCode: "XAF", countryCode: "CM", flag: "🇨🇲" },
  { value: "CA", label: "Canada", phoneCode: "+1", currencyCode: "CAD", countryCode: "CA", flag: "🇨🇦" },
  { value: "CV", label: "Cape Verde", phoneCode: "+238", currencyCode: "CVE", countryCode: "CV", flag: "🇨🇻" },
  {
    value: "CF",
    label: "Central African Republic",
    phoneCode: "+236",
    currencyCode: "XAF",
    countryCode: "CF",
    flag: "🇨🇫",
  },
  { value: "TD", label: "Chad", phoneCode: "+235", currencyCode: "XAF", countryCode: "TD", flag: "🇹🇩" },
  { value: "CL", label: "Chile", phoneCode: "+56", currencyCode: "CLP", countryCode: "CL", flag: "🇨🇱" },
  { value: "CN", label: "China", phoneCode: "+86", currencyCode: "CNY", countryCode: "CN", flag: "🇨🇳" },
  { value: "CO", label: "Colombia", phoneCode: "+57", currencyCode: "COP", countryCode: "CO", flag: "🇨🇴" },
  { value: "KM", label: "Comoros", phoneCode: "+269", currencyCode: "KMF", countryCode: "KM", flag: "🇰🇲" },
  { value: "CG", label: "Congo", phoneCode: "+242", currencyCode: "XAF", countryCode: "CG", flag: "🇨🇬" },
  { value: "CR", label: "Costa Rica", phoneCode: "+506", currencyCode: "CRC", countryCode: "CR", flag: "🇨🇷" },
  { value: "HR", label: "Croatia", phoneCode: "+385", currencyCode: "HRK", countryCode: "HR", flag: "🇭🇷" },
  { value: "CU", label: "Cuba", phoneCode: "+53", currencyCode: "CUP", countryCode: "CU", flag: "🇨🇺" },
  { value: "CY", label: "Cyprus", phoneCode: "+357", currencyCode: "EUR", countryCode: "CY", flag: "🇨🇾" },
  { value: "CZ", label: "Czech Republic", phoneCode: "+420", currencyCode: "CZK", countryCode: "CZ", flag: "🇨🇿" },
  { value: "DK", label: "Denmark", phoneCode: "+45", currencyCode: "DKK", countryCode: "DK", flag: "🇩🇰" },
  { value: "DJ", label: "Djibouti", phoneCode: "+253", currencyCode: "DJF", countryCode: "DJ", flag: "🇩🇯" },
  { value: "DM", label: "Dominica", phoneCode: "+1767", currencyCode: "XCD", countryCode: "DM", flag: "🇩🇲" },
  { value: "DO", label: "Dominican Republic", phoneCode: "+1849", currencyCode: "DOP", countryCode: "DO", flag: "🇩🇴" },
  { value: "EC", label: "Ecuador", phoneCode: "+593", currencyCode: "USD", countryCode: "EC", flag: "🇪🇨" },
  { value: "EG", label: "Egypt", phoneCode: "+20", currencyCode: "EGP", countryCode: "EG", flag: "🇪🇬" },
  { value: "SV", label: "El Salvador", phoneCode: "+503", currencyCode: "USD", countryCode: "SV", flag: "🇸🇻" },
  { value: "GQ", label: "Equatorial Guinea", phoneCode: "+240", currencyCode: "XAF", countryCode: "GQ", flag: "🇬🇶" },
  { value: "ER", label: "Eritrea", phoneCode: "+291", currencyCode: "ERN", countryCode: "ER", flag: "🇪🇷" },
  { value: "EE", label: "Estonia", phoneCode: "+372", currencyCode: "EUR", countryCode: "EE", flag: "🇪🇪" },
  { value: "ET", label: "Ethiopia", phoneCode: "+251", currencyCode: "ETB", countryCode: "ET", flag: "🇪🇹" },
  { value: "FJ", label: "Fiji", phoneCode: "+679", currencyCode: "FJD", countryCode: "FJ", flag: "🇫🇯" },
  { value: "FI", label: "Finland", phoneCode: "+358", currencyCode: "EUR", countryCode: "FI", flag: "🇫🇮" },
  { value: "FR", label: "France", phoneCode: "+33", currencyCode: "EUR", countryCode: "FR", flag: "🇫🇷" },
  { value: "GA", label: "Gabon", phoneCode: "+241", currencyCode: "XAF", countryCode: "GA", flag: "🇬🇦" },
  { value: "GM", label: "Gambia", phoneCode: "+220", currencyCode: "GMD", countryCode: "GM", flag: "🇬🇲" },
  { value: "GE", label: "Georgia", phoneCode: "+995", currencyCode: "GEL", countryCode: "GE", flag: "🇬🇪" },
  { value: "DE", label: "Germany", phoneCode: "+49", currencyCode: "EUR", countryCode: "DE", flag: "🇩🇪" },
  { value: "GH", label: "Ghana", phoneCode: "+233", currencyCode: "GHS", countryCode: "GH", flag: "🇬🇭" },
  { value: "GR", label: "Greece", phoneCode: "+30", currencyCode: "EUR", countryCode: "GR", flag: "🇬🇷" },
  { value: "GD", label: "Grenada", phoneCode: "+1473", currencyCode: "XCD", countryCode: "GD", flag: "🇬🇩" },
  { value: "GT", label: "Guatemala", phoneCode: "+502", currencyCode: "GTQ", countryCode: "GT", flag: "🇬🇹" },
  { value: "GN", label: "Guinea", phoneCode: "+224", currencyCode: "GNF", countryCode: "GN", flag: "🇬🇳" },
  { value: "GW", label: "Guinea-Bissau", phoneCode: "+245", currencyCode: "XOF", countryCode: "GW", flag: "🇬🇼" },
  { value: "GY", label: "Guyana", phoneCode: "+592", currencyCode: "GYD", countryCode: "GY", flag: "🇬🇾" },
  { value: "HT", label: "Haiti", phoneCode: "+509", currencyCode: "HTG", countryCode: "HT", flag: "🇭🇹" },
  { value: "HN", label: "Honduras", phoneCode: "+504", currencyCode: "HNL", countryCode: "HN", flag: "🇭🇳" },
  { value: "HU", label: "Hungary", phoneCode: "+36", currencyCode: "HUF", countryCode: "HU", flag: "🇭🇺" },
  { value: "IS", label: "Iceland", phoneCode: "+354", currencyCode: "ISK", countryCode: "IS", flag: "🇮🇸" },
  { value: "IN", label: "India", phoneCode: "+91", currencyCode: "INR", countryCode: "IN", flag: "🇮🇳" },
  { value: "ID", label: "Indonesia", phoneCode: "+62", currencyCode: "IDR", countryCode: "ID", flag: "🇮🇩" },
  { value: "IR", label: "Iran", phoneCode: "+98", currencyCode: "IRR", countryCode: "IR", flag: "🇮🇷" },
  { value: "IQ", label: "Iraq", phoneCode: "+964", currencyCode: "IQD", countryCode: "IQ", flag: "🇮🇶" },
  { value: "IE", label: "Ireland", phoneCode: "+353", currencyCode: "EUR", countryCode: "IE", flag: "🇮🇪" },
  { value: "IL", label: "Israel", phoneCode: "+972", currencyCode: "ILS", countryCode: "IL", flag: "🇮🇱" },
  { value: "IT", label: "Italy", phoneCode: "+39", currencyCode: "EUR", countryCode: "IT", flag: "🇮🇹" },
  { value: "CI", label: "Ivory Coast", phoneCode: "+225", currencyCode: "XOF", countryCode: "CI", flag: "🇨🇮" },
  { value: "JM", label: "Jamaica", phoneCode: "+1876", currencyCode: "JMD", countryCode: "JM", flag: "🇯🇲" },
  { value: "JP", label: "Japan", phoneCode: "+81", currencyCode: "JPY", countryCode: "JP", flag: "🇯🇵" },
  { value: "JO", label: "Jordan", phoneCode: "+962", currencyCode: "JOD", countryCode: "JO", flag: "🇯🇴" },
  { value: "KZ", label: "Kazakhstan", phoneCode: "+7", currencyCode: "KZT", countryCode: "KZ", flag: "🇰🇿" },
  { value: "KE", label: "Kenya", phoneCode: "+254", currencyCode: "KES", countryCode: "KE", flag: "🇰🇪" },
  { value: "KI", label: "Kiribati", phoneCode: "+686", currencyCode: "AUD", countryCode: "KI", flag: "🇰🇮" },
  { value: "KP", label: "North Korea", phoneCode: "+850", currencyCode: "KPW", countryCode: "KP", flag: "🇰🇵" },
  { value: "KR", label: "South Korea", phoneCode: "+82", currencyCode: "KRW", countryCode: "KR", flag: "🇰🇷" },
  { value: "KW", label: "Kuwait", phoneCode: "+965", currencyCode: "KWD", countryCode: "KW", flag: "🇰🇼" },
  { value: "KG", label: "Kyrgyzstan", phoneCode: "+996", currencyCode: "KGS", countryCode: "KG", flag: "🇰🇬" },
  { value: "LA", label: "Laos", phoneCode: "+856", currencyCode: "LAK", countryCode: "LA", flag: "🇱🇦" },
  { value: "LV", label: "Latvia", phoneCode: "+371", currencyCode: "EUR", countryCode: "LV", flag: "🇱🇻" },
  { value: "LB", label: "Lebanon", phoneCode: "+961", currencyCode: "LBP", countryCode: "LB", flag: "🇱🇧" },
  { value: "LS", label: "Lesotho", phoneCode: "+266", currencyCode: "LSL", countryCode: "LS", flag: "🇱🇸" },
  { value: "LR", label: "Liberia", phoneCode: "+231", currencyCode: "LRD", countryCode: "LR", flag: "🇱🇷" },
  { value: "LY", label: "Libya", phoneCode: "+218", currencyCode: "LYD", countryCode: "LY", flag: "🇱🇾" },
  { value: "LI", label: "Liechtenstein", phoneCode: "+423", currencyCode: "CHF", countryCode: "LI", flag: "🇱🇮" },
  { value: "LT", label: "Lithuania", phoneCode: "+370", currencyCode: "EUR", countryCode: "LT", flag: "🇱🇹" },
  { value: "LU", label: "Luxembourg", phoneCode: "+352", currencyCode: "EUR", countryCode: "LU", flag: "🇱🇺" },
  { value: "MG", label: "Madagascar", phoneCode: "+261", currencyCode: "MGA", countryCode: "MG", flag: "🇲🇬" },
  { value: "MW", label: "Malawi", phoneCode: "+265", currencyCode: "MWK", countryCode: "MW", flag: "🇲🇼" },
  { value: "MY", label: "Malaysia", phoneCode: "+60", currencyCode: "MYR", countryCode: "MY", flag: "🇲🇾" },
  { value: "MV", label: "Maldives", phoneCode: "+960", currencyCode: "MVR", countryCode: "MV", flag: "🇲🇻" },
  { value: "ML", label: "Mali", phoneCode: "+223", currencyCode: "XOF", countryCode: "ML", flag: "🇲🇱" },
  { value: "MT", label: "Malta", phoneCode: "+356", currencyCode: "EUR", countryCode: "MT", flag: "🇲🇹" },
  { value: "MH", label: "Marshall Islands", phoneCode: "+692", currencyCode: "USD", countryCode: "MH", flag: "🇲🇭" },
  { value: "MR", label: "Mauritania", phoneCode: "+222", currencyCode: "MRU", countryCode: "MR", flag: "🇲🇷" },
  { value: "MU", label: "Mauritius", phoneCode: "+230", currencyCode: "MUR", countryCode: "MU", flag: "🇲🇺" },
  { value: "MX", label: "Mexico", phoneCode: "+52", currencyCode: "MXN", countryCode: "MX", flag: "🇲🇽" },
  { value: "FM", label: "Micronesia", phoneCode: "+691", currencyCode: "USD", countryCode: "FM", flag: "🇫🇲" },
  { value: "MD", label: "Moldova", phoneCode: "+373", currencyCode: "MDL", countryCode: "MD", flag: "🇲🇩" },
  { value: "MC", label: "Monaco", phoneCode: "+377", currencyCode: "EUR", countryCode: "MC", flag: "🇲🇨" },
  { value: "MN", label: "Mongolia", phoneCode: "+976", currencyCode: "MNT", countryCode: "MN", flag: "🇲🇳" },
  { value: "ME", label: "Montenegro", phoneCode: "+382", currencyCode: "EUR", countryCode: "ME", flag: "🇲🇪" },
  { value: "MA", label: "Morocco", phoneCode: "+212", currencyCode: "MAD", countryCode: "MA", flag: "🇲🇦" },
  { value: "MZ", label: "Mozambique", phoneCode: "+258", currencyCode: "MZN", countryCode: "MZ", flag: "🇲🇿" },
  { value: "MM", label: "Myanmar", phoneCode: "+95", currencyCode: "MMK", countryCode: "MM", flag: "🇲🇲" },
  { value: "NA", label: "Namibia", phoneCode: "+264", currencyCode: "NAD", countryCode: "NA", flag: "🇳🇦" },
  { value: "NR", label: "Nauru", phoneCode: "+674", currencyCode: "AUD", countryCode: "NR", flag: "🇳🇷" },
  { value: "NP", label: "Nepal", phoneCode: "+977", currencyCode: "NPR", countryCode: "NP", flag: "🇳🇵" },
  { value: "NL", label: "Netherlands", phoneCode: "+31", currencyCode: "EUR", countryCode: "NL", flag: "🇳🇱" },
  { value: "NZ", label: "New Zealand", phoneCode: "+64", currencyCode: "NZD", countryCode: "NZ", flag: "🇳🇿" },
  { value: "NI", label: "Nicaragua", phoneCode: "+505", currencyCode: "NIO", countryCode: "NI", flag: "🇳🇮" },
  { value: "NE", label: "Niger", phoneCode: "+227", currencyCode: "XOF", countryCode: "NE", flag: "🇳🇪" },
  { value: "NG", label: "Nigeria", phoneCode: "+234", currencyCode: "NGN", countryCode: "NG", flag: "🇳🇬" },
  { value: "MK", label: "North Macedonia", phoneCode: "+389", currencyCode: "MKD", countryCode: "MK", flag: "🇲🇰" },
  { value: "NO", label: "Norway", phoneCode: "+47", currencyCode: "NOK", countryCode: "NO", flag: "🇳🇴" },
  { value: "OM", label: "Oman", phoneCode: "+968", currencyCode: "OMR", countryCode: "OM", flag: "🇴🇲" },
  { value: "PK", label: "Pakistan", phoneCode: "+92", currencyCode: "PKR", countryCode: "PK", flag: "🇵🇰" },
  { value: "PW", label: "Palau", phoneCode: "+680", currencyCode: "USD", countryCode: "PW", flag: "🇵🇼" },
  { value: "PS", label: "Palestine", phoneCode: "+970", currencyCode: "ILS", countryCode: "PS", flag: "🇵🇸" },
  { value: "PA", label: "Panama", phoneCode: "+507", currencyCode: "USD", countryCode: "PA", flag: "🇵🇦" },
  { value: "PG", label: "Papua New Guinea", phoneCode: "+675", currencyCode: "PGK", countryCode: "PG", flag: "🇵🇬" },
  { value: "PY", label: "Paraguay", phoneCode: "+595", currencyCode: "PYG", countryCode: "PY", flag: "🇵🇾" },
  { value: "PE", label: "Peru", phoneCode: "+51", currencyCode: "PEN", countryCode: "PE", flag: "🇵🇪" },
  { value: "PH", label: "Philippines", phoneCode: "+63", currencyCode: "PHP", countryCode: "PH", flag: "🇵🇭" },
  { value: "PL", label: "Poland", phoneCode: "+48", currencyCode: "PLN", countryCode: "PL", flag: "🇵🇱" },
  { value: "PT", label: "Portugal", phoneCode: "+351", currencyCode: "EUR", countryCode: "PT", flag: "🇵🇹" },
  { value: "QA", label: "Qatar", phoneCode: "+974", currencyCode: "QAR", countryCode: "QA", flag: "🇶🇦" },
  { value: "RO", label: "Romania", phoneCode: "+40", currencyCode: "RON", countryCode: "RO", flag: "🇷🇴" },
  { value: "RU", label: "Russia", phoneCode: "+7", currencyCode: "RUB", countryCode: "RU", flag: "🇷🇺" },
  { value: "RW", label: "Rwanda", phoneCode: "+250", currencyCode: "RWF", countryCode: "RW", flag: "🇷🇼" },
  {
    value: "KN",
    label: "Saint Kitts and Nevis",
    phoneCode: "+1869",
    currencyCode: "XCD",
    countryCode: "KN",
    flag: "🇰🇳",
  },
  { value: "LC", label: "Saint Lucia", phoneCode: "+1758", currencyCode: "XCD", countryCode: "LC", flag: "🇱🇨" },
  {
    value: "VC",
    label: "Saint Vincent and the Grenadines",
    phoneCode: "+1784",
    currencyCode: "XCD",
    countryCode: "VC",
    flag: "🇻🇨",
  },
  { value: "WS", label: "Samoa", phoneCode: "+685", currencyCode: "WST", countryCode: "WS", flag: "🇼🇸" },
  { value: "SM", label: "San Marino", phoneCode: "+378", currencyCode: "EUR", countryCode: "SM", flag: "🇸🇲" },
  {
    value: "ST",
    label: "Sao Tome and Principe",
    phoneCode: "+239",
    currencyCode: "STD",
    countryCode: "ST",
    flag: "🇸🇹",
  },
  { value: "SA", label: "Saudi Arabia", phoneCode: "+966", currencyCode: "SAR", countryCode: "SA", flag: "🇸🇦" },
  { value: "SN", label: "Senegal", phoneCode: "+221", currencyCode: "XOF", countryCode: "SN", flag: "🇸🇳" },
  { value: "RS", label: "Serbia", phoneCode: "+381", currencyCode: "RSD", countryCode: "RS", flag: "🇷🇸" },
  { value: "SC", label: "Seychelles", phoneCode: "+248", currencyCode: "SCR", countryCode: "SC", flag: "🇸🇨" },
  { value: "SL", label: "Sierra Leone", phoneCode: "+232", currencyCode: "SLL", countryCode: "SL", flag: "🇸🇱" },
  { value: "SG", label: "Singapore", phoneCode: "+65", currencyCode: "SGD", countryCode: "SG", flag: "🇸🇬" },
  { value: "SK", label: "Slovakia", phoneCode: "+421", currencyCode: "EUR", countryCode: "SK", flag: "🇸🇰" },
  { value: "SI", label: "Slovenia", phoneCode: "+386", currencyCode: "EUR", countryCode: "SI", flag: "🇸🇮" },
  { value: "SB", label: "Solomon Islands", phoneCode: "+677", currencyCode: "SBD", countryCode: "SB", flag: "🇸🇧" },
  { value: "SO", label: "Somalia", phoneCode: "+252", currencyCode: "SOS", countryCode: "SO", flag: "🇸🇴" },
  { value: "ZA", label: "South Africa", phoneCode: "+27", currencyCode: "ZAR", countryCode: "ZA", flag: "🇿🇦" },
  { value: "ES", label: "Spain", phoneCode: "+34", currencyCode: "EUR", countryCode: "ES", flag: "🇪🇸" },
  { value: "LK", label: "Sri Lanka", phoneCode: "+94", currencyCode: "LKR", countryCode: "LK", flag: "🇱🇰" },
  { value: "SD", label: "Sudan", phoneCode: "+249", currencyCode: "SDG", countryCode: "SD", flag: "🇸🇩" },
  { value: "SR", label: "Suriname", phoneCode: "+597", currencyCode: "SRD", countryCode: "SR", flag: "🇸🇷" },
  { value: "SZ", label: "Eswatini", phoneCode: "+268", currencyCode: "SZL", countryCode: "SZ", flag: "🇸🇿" },
  { value: "SE", label: "Sweden", phoneCode: "+46", currencyCode: "SEK", countryCode: "SE", flag: "🇸🇪" },
  { value: "CH", label: "Switzerland", phoneCode: "+41", currencyCode: "CHF", countryCode: "CH", flag: "🇨🇭" },
  { value: "SY", label: "Syria", phoneCode: "+963", currencyCode: "SYP", countryCode: "SY", flag: "🇸🇾" },

  { value: "TW", label: "Taiwan", phoneCode: "+886", currencyCode: "TWD", countryCode: "TW", flag: "🇹🇼" },
  { value: "TJ", label: "Tajikistan", phoneCode: "+992", currencyCode: "TJS", countryCode: "TJ", flag: "🇹🇯" },
  { value: "TZ", label: "Tanzania", phoneCode: "+255", currencyCode: "TZS", countryCode: "TZ", flag: "🇹🇿" },
  { value: "TH", label: "Thailand", phoneCode: "+66", currencyCode: "THB", countryCode: "TH", flag: "🇹🇭" },
  { value: "TL", label: "Timor-Leste", phoneCode: "+670", currencyCode: "USD", countryCode: "TL", flag: "🇹🇱" },
  { value: "TG", label: "Togo", phoneCode: "+228", currencyCode: "XOF", countryCode: "TG", flag: "🇹🇬" },
  { value: "TO", label: "Tonga", phoneCode: "+676", currencyCode: "TOP", countryCode: "TO", flag: "🇹🇴" },
  { value: "TT", label: "Trinidad and Tobago", phoneCode: "+1868", currencyCode: "TTD", countryCode: "TT", flag: "🇹🇹" },
  { value: "TN", label: "Tunisia", phoneCode: "+216", currencyCode: "TND", countryCode: "TN", flag: "🇹🇳" },
  { value: "TR", label: "Turkey", phoneCode: "+90", currencyCode: "TRY", countryCode: "TR", flag: "🇹🇷" },
  { value: "TM", label: "Turkmenistan", phoneCode: "+993", currencyCode: "TMT", countryCode: "TM", flag: "🇹🇲" },
  { value: "TV", label: "Tuvalu", phoneCode: "+688", currencyCode: "AUD", countryCode: "TV", flag: "🇹🇻" },
  { value: "UG", label: "Uganda", phoneCode: "+256", currencyCode: "UGX", countryCode: "UG", flag: "🇺🇬" },
  { value: "UA", label: "Ukraine", phoneCode: "+380", currencyCode: "UAH", countryCode: "UA", flag: "🇺🇦" },
  { value: "AE", label: "United Arab Emirates", phoneCode: "+971", currencyCode: "AED", countryCode: "AE", flag: "🇦🇪" },
  { value: "GB", label: "United Kingdom", phoneCode: "+44", currencyCode: "GBP", countryCode: "GB", flag: "🇬🇧" },
  { value: "US", label: "United States", phoneCode: "+1", currencyCode: "USD", countryCode: "US", flag: "🇺🇸" },
  { value: "UY", label: "Uruguay", phoneCode: "+598", currencyCode: "UYU", countryCode: "UY", flag: "🇺🇾" },
  { value: "UZ", label: "Uzbekistan", phoneCode: "+998", currencyCode: "UZS", countryCode: "UZ", flag: "🇺🇿" },
  { value: "VU", label: "Vanuatu", phoneCode: "+678", currencyCode: "VUV", countryCode: "VU", flag: "🇻🇺" },
  { value: "VA", label: "Vatican City", phoneCode: "+379", currencyCode: "EUR", countryCode: "VA", flag: "🇻🇦" },
  { value: "VE", label: "Venezuela", phoneCode: "+58", currencyCode: "VES", countryCode: "VE", flag: "🇻🇪" },
  { value: "VN", label: "Vietnam", phoneCode: "+84", currencyCode: "VND", countryCode: "VN", flag: "🇻🇳" },
  { value: "YE", label: "Yemen", phoneCode: "+967", currencyCode: "YER", countryCode: "YE", flag: "🇾🇪" },
  { value: "ZM", label: "Zambia", phoneCode: "+260", currencyCode: "ZMW", countryCode: "ZM", flag: "🇿🇲" },
  { value: "ZW", label: "Zimbabwe", phoneCode: "+263", currencyCode: "ZWL", countryCode: "ZW", flag: "🇿🇼" },
];
